export const FLIGHT_FETCH_REQUEST = "FLIGHT_FETCH_REQUEST"
export const FLIGHT_FETCH_SUCCESS = "FLIGHT_FETCH_SUCCESS"
export const FLIGHT_FETCH_FAIL = "FLIGHT_FETCH_FAIL"
export const FLIGHT_FETCH_RESET = "FLIGHT_FETCH_RESET"

export const FLIGHT_ADD_REQUEST = "FLIGHT_ADD_REQUEST"
export const FLIGHT_ADD_SUCCESS = "FLIGHT_ADD_SUCCESS"
export const FLIGHT_ADD_FAIL = "FLIGHT_ADD_FAIL"
export const FLIGHT_ADD_RESET = "FLIGHT_ADD_RESET"

export const FLIGHT_CANCEL_REQUEST= "FLIGHT_CANCEL_REQUEST"
export const FLIGHT_CANCEL_SUCCESS= "FLIGHT_CANCEL_SUCCESS"
export const FLIGHT_CANCEL_FAIL= "FLIGHT_CANCEL_FAIL"
export const FLIGHT_CANCEL_RESET= "FLIGHT_CANCEL_RESET"

